listorder/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('management/', views.ManagementView.as_view(), name='management')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listorder.urls')),
]

listorder/models.py
from django.db import models

class PizzaType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Pizza(models.Model):
    pizza_type_id = models.ForeignKey(PizzaType, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return "{0} - {1}".format(self.name, self.price)


class Transaction(models.Model):
    pizza_id = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return "{0} - {1}".format(self.pizza_id, self.quantity)

listorder/forms.py
from django import forms
from django.db import models
from .models import PizzaType, Pizza, Transaction


class PizzaTypeForm(forms.ModelForm):
    class Meta:
        model = PizzaType
        fields = ['name']

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['pizza_type_id', 'name', 'price']


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['pizza_id', 'quantity']

class SearchForm(forms.Form):
    name = forms.CharField(required=False)

listorder/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, TemplateView
from .models import Pizza, PizzaType, Transaction
from django.conf import settings
from  .forms import PizzaForm, TransactionForm, SearchForm


# Create your views here.
class HomeView(ListView):
    model = Transaction
    form_class = SearchForm
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['timezone'] = settings.TIME_ZONE
        context['search_form'] = SearchForm
        return context

    def get_queryset(self): #search function
        name = self.form_class(self.request.GET)
        if name.is_valid():
            order_list = self.model.objects.filter(pizza_id__name__contains='{0}'.format(self.request.GET.get('name', '')))
            return order_list.order_by('-pk') #order by descending



class ManagementView(TemplateView):
    template_name = 'management.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form_pizza'] = PizzaForm
        context['form_transaction'] = TransactionForm
        return context

    def post(self, request):
        if request.method == 'POST':
            form = TransactionForm(request.POST) if 'pizza_id' in request.POST else PizzaForm(request.POST)

            if form.is_valid():
                form.save()
                return HttpResponse('success!!!')

listorder/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pizza Order</title>
    {% load static %}
    {% load mathfilters %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index'%}">Pizza</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'management' %}">Management</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">


          <h5> Date : {% now "jS F Y h:i：a" %}  -  {{ timezone }}</h5>


          {% for pizza in transaction_list %}
            <!-- Blog Post -->
            <div class="card mb-4">

              <div class="card-body">
                <h2 class="card-title">{{ pizza.pizza_id }}</h2>
                <p class="card-text">
                    Price : {{ pizza.pizza_id.price }} <br />
                    Pizza Type : {{ pizza.pizza_id.pizza_type_id }} <br />
                    Total Pizza Sold : {{ pizza.quantity }}<br />
                    Total Amount : {{ pizza.quantity|mul:pizza.pizza_id.price }}
                </p>
              </div>

            </div>
          {% endfor %}




      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <form method="get">
                {% csrf_token %}
                  {{ search_form.as_p }}
                  <input type="submit" value="Add">
              </form>

            </div>
          </div>
        </div>


      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Pizza Company 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

listorder/templates/management.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
    {% load static %}
  <title>PizzaApp</title>
  <!-- Bootstrap core CSS -->
  <link href="{%  static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{%  static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Pizza Management </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">

        <h1 class="mt-4">Add Pizza</h1>

        <form method="post">
          {% csrf_token %}
            {{ form_pizza.as_p }}
            <input type="submit" value="Add">
        </form>

          <h1 class="mt-4">Add Transaction</h1>

        <form method="post">
          {% csrf_token %}
            {{ form_transaction.as_p }}
            <input type="submit" value="Add">
        </form>
      </div>


    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js'  %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>